apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-classification
  template:
    metadata:
      labels:
        app: flower-classification
    spec:
      containers:
        - name: flower-classification-container
          image: nishantrout99/iris-classifier:0.1.1
          command: ["gunicorn", "-w", "3", "-b", "0.0.0.0:8000", "src.app:app"]
          ports:
            - containerPort: 8000
